In [ ]:
import numpy as np
import pandas as pd

xa = '/home/santi3223/contest game/IA/obiaprob1/sample_submission.csv'
xb = '/home/santi3223/contest game/IA/obiaprob1/test.csv'
xc = '/home/santi3223/contest game/IA/obiaprob1/train.csv'

ssub = pd.read_csv(xa)
tst = pd.read_csv(xb)
trn = pd.read_csv(xc)

Importo las librerias np ya que lo usare para calcular RMSE luego, y pandas ya que se usa para csv
Hago output del input para saber con que se trabaja.

In [2]:
ssub

       id   quality
0       3  5.656455
1      12  5.656455
2      32  5.656455
3      42  5.656455
4      43  5.656455
..    ...       ...
224  1568  5.656455
225  1577  5.656455
226  1578  5.656455
227  1586  5.656455
228  1590  5.656455

[229 rows x 2 columns]

In [3]:
tst

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,id
0,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,3
1,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.99430,3.58,0.52,9.9,12
2,8.3,0.655,0.12,2.3,0.083,15.0,113.0,0.99660,3.17,0.66,9.8,32
3,7.5,0.490,0.20,2.6,0.332,8.0,14.0,0.99680,3.21,0.90,10.5,42
4,8.1,0.660,0.22,2.2,0.069,9.0,23.0,0.99680,3.30,1.20,10.3,43
...,...,...,...,...,...,...,...,...,...,...,...,...
224,7.0,0.560,0.13,1.6,0.077,25.0,42.0,0.99629,3.34,0.59,9.2,1568
225,6.2,0.700,0.15,5.1,0.076,13.0,27.0,0.99622,3.54,0.60,11.9,1577
226,6.8,0.670,0.15,1.8,0.118,13.0,20.0,0.99540,3.42,0.67,11.3,1578
227,7.5,0.310,0.41,2.4,0.065,34.0,60.0,0.99492,3.34,0.85,11.4,1586
228,6.3,0.550,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,1590

In [4]:
tst.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'id'],
      dtype='str')

In [5]:
trn

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,2
3,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,4
4,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.99780,3.51,0.56,9.4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
909,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
910,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
911,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5,1594
912,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595
913,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5,1597

In [6]:
trn.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'id'],
      dtype='str')

Importo train test split, ya que es necesario para entrenar al modelo. Gradient Boosting ya que es el mejor modelo para esta tarea, mejor que random forest o dec tree.
Y MSE, ya que es necesario para RMSE.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

Ahora hago X y 'y', donde y tiene la parte de calidad del vino, y X la info que no la incluye
con train test split, divido el test.csv, x y 'y'.

In [ ]:
X = trn.drop('quality', axis=1) 
y = trn['quality']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

el modelo es gradient boost, y lo entreno con la parte de x y 'y' que es para entrenarlo

In [9]:
model = GradientBoostingRegressor(random_state=1)
model.fit(X_train, y_train)

GradientBoostingRegressor(random_state=1)

hago una prediccion con el test de x, y calculo el MSE con esa seccion, para ver que esta bien o mal y poder ajustar en alguna otra seccion

In [10]:

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)  # Calcular RMSE

print(f'Mean Squared Error: {mse:.2f}')
print(f'Root Mean Squared Error: {rmse:.2f}')  # Imprimir RMSE

Mean Squared Error: 0.45
Root Mean Squared Error: 0.67

ahora el output se va a resultados, con una prediccion de test.csv

In [11]:
tst_features = tst
predicciones_test = model.predict(tst_features)

resultados = pd.DataFrame({'id': tst['id'], 'quality': predicciones_test})

resultados.to_csv('predicciones.csv', index=False)